### ISSUE TITLE
Include BasicRouter from RapidSmith

### ISSUE THREAD

**Issue by nelsobe** [byuccl/RapidSmith2#142]
RapidSmith had a BasicRouter framework written by Chris Lavin.  It would be useful to update it to RapidSmith2 for inclusion in the release.

**Comment by trharoldsen** [comment]
With the inclusion of the AStar router example, I move that we close this issue.

**Comment by DallonTG** [comment]
Closing this. @nelsobe, if you feel like there would still be benefit in updating the BasicRouter framework, feel free to re-open this!
