### ISSUE TITLE
Remove UNKNOWN enum from NetType

### ISSUE THREAD

**Issue by trharoldsen** [byuccl/RapidSmith2#166]
UNKNOWN is one of the possible enumerations for the type of net, in addition to WIRE, VCC, and GND.  It is currently unused and is unknown where it would be used.  Since it serves no purpose, we might as well remove it.

**Comment by nelsobe** [comment]
Agreed.  I wondered about that as I was looking through this as I was documenting.

**Comment by xrtc** [comment]
Resolved in #182
