### ISSUE TITLE
Remove JDOMException from being thrown at the top level

### ISSUE THREAD

**Issue by ttown523** [byuccl/RapidSmith2#172]
The function `VivadoInterface.loadTCP` currently throws a JDOMException. The problem is that the user would need to include the jars for JDOM in order to use it. RapidSmith should be standalone, and so we should not be throwing this exception at the top level.

The exception originates in the constructor for `CellLibrary` , and should be handles internally there and wrapped in a generic parse exception.

**Comment by trharoldsen** [comment]
Resolved in #173
