### ISSUE TITLE
Move to Latest QT Jambi

### ISSUE THREAD

**Issue by nelsobe** [byuccl/RapidSmith2#174]
Now that QT Jambi 64-bit is supported, we ought to consider moving to just 64-bit versions and, at the same time, upgrading to the latest.  This may or may not require any changes to our programs that need it.  Currently the only program that requires it is DeviceBrowser and VSRT.    We could also consider re-doing DesignExplorer to work with RS2 and this latest QT.

**Comment by xrtc** [comment]
Resolved in #178
