### ISSUE TITLE
Move VivadoConstraints in Design into Properties

### ISSUE THREAD

**Issue by trharoldsen** [byuccl/RapidSmith2#179]
Could we remove the additional vivadoConstraints field in CellDesign and move it into the properties.  We could add a CONSTRAINTS PropertyType to identify them.  The main issue I see is that the constraints do not have a name associated with them.

**Comment by ttown523** [comment]
If you look at the `XdcConstraint` class, there is a command field, and a options field. XDC constraints don't really have names, they are essentially TCL statements. A user could use the code:

`design.getVivadoConstraints().stream().filter(c -> c.getCommandName().equals("set_property")).collect(Collectors.toList());`

to find all of the Vivado constraints that set some sort of property. I think for now, we should leave it the way it is until we implement a smarter way to handle XDC constraints in the future.
