### ISSUE TITLE
Updates to RouteTree class

### ISSUE THREAD

**Issue by trharoldsen** [byuccl/RapidSmith2#191]
setSourceTree should be private -- it can be accomplished with the addConnection(Connection, RouteTree) method.
setConnection should be private -- same as above
Remove cost field from tree -- This method is only seldom used, takes up space and an int is not always what the user wants (the may want double).  For cases where cost is useful, they can create a map of trees -> costs or extend RouteTree
Make RouteTree extensible -- extending the class would require reimplementing the addConnection class to create an instance of the RouteTree subclass.  We could probably due something with creating an abstract base class which the user can extend that doesn't implement the addConnection method forcing them to extend it.

**Comment by mcrossen** [comment]
Making the RouteTree class extensible will basically require changing the entire class. The difficulty comes from all the methods where RouteTree references itself in both return and parameter types. Sadly, Java has poor support for recursive inheritable data structures. We'll talk more the next time we meet. I have some ideas we can talk about then.

**Comment by trharoldsen** [comment]
see #231

**Comment by trharoldsen** [comment]
Reference pr #323

**Comment by DallonTG** [comment]
This seems resolved so I'm closing it.
