### ISSUE TITLE
getWire(wireName) methods in Site and Tile

### ISSUE THREAD

**Issue by trharoldsen** [byuccl/RapidSmith2#192]
Create a method to return the wire in the given tile/site with the specified name.  Internally this would look up the enumeration from the wire enumerator and return the TileWire/SiteWire object.  This hides the last remaining common need for users accessing the WireEnumerator and makes the code cleaner.
Simplifies
`new TileWire(tile, wireEnumerator.getWireEnum(wireName))`
to 
`tile.getWire(wireName)`

**Comment by nelsobe** [comment]
Talk to Travis about this one to make sure what is wanted is clear...

**Comment by trharoldsen** [comment]
I don't know which commit implemented them, but the methods are in the code as of commit 11b02b7
