### ISSUE TITLE
Unroute net does not unroute everything

### ISSUE THREAD

**Issue by mjc31511** [byuccl/RapidSmith2#229]
I fixed this issue by setting the belPinToSinkRTMap to null and the sitePinToRTMap to null in the unroute function so it now looks like this:

```
public void unroute() {
		intersiteRoutes = null;
		routedSinks = null;
		belPinToSinkRTMap = null;
		sitePinToRTMap = null;
	}
```

**Comment by DallonTG** [comment]
It looks like this was addressed in #253 and then unroute() was renamed to unrouteFull() in #281. Additionally, you said today that the unroute method now seems to unroute everything.
