### ISSUE TITLE
SitePins of BelPins doesn't factor in RouteThroughs

### ISSUE THREAD

**Issue by trharoldsen** [byuccl/RapidSmith2#260]
BelPin::getSitePins is supposed to provide the site pins that drive the BelPins.  The returned value though does not factor in BEL routethroughs (it is generated directly from the primitive defs info).  Is this the behavior we want or do we want to account for BEL routethroughs?

**Comment by ttown523** [comment]
We should probably factor in routethroughs as well. I'm assuming this will be an update to the device generator?

**Comment by trharoldsen** [comment]
Yes, this would be in the device genrator.

**Comment by nelsobe** [comment]
Issues to keep in mind:
1. This routine is currently not being used anywhere in the code base we can find.
2. While XDLRC files do contain information on site route-throughs (A1 input --> A output pin on a slice), they do not contain information on BEL route-throughs (A1 bel pin --> O6 bel pin).  That information is represented in the familyInfo.xml file.  However, that information is not being queried by this routine and therefore what is returned does not reflect possible BEL route-through paths.

**Comment by trharoldsen** [comment]
I vote we remove the subroutine.  Anyone opposed to this solution?
