### ISSUE TITLE
Update Junit 5 GA Release

### ISSUE THREAD

**Issue by trharoldsen** [byuccl/RapidSmith2#266]
General Availability release of JUnit 5 has come out and we should update to it from our current beta version.  Updating should be pretty straight forward with mainly changing the release number in Gradle.  I think some of the package locations may have changed so we may have some simple updating of a couple tests to perform.

**Comment by nelsobe** [comment]
This is also related to #220?

**Comment by mcrossen** [comment]
fixed by PR #231
