### ISSUE TITLE
Change Tile.getSinks and Tile.getSources methods to reference sites

### ISSUE THREAD

**Issue by trharoldsen** [byuccl/RapidSmith2#267]
We currently have dedicated data structures holding information about the sources and the sinks in the tiles.  This information is redundant as we also have it for the site objects.  I also suspect that these methods are seldom used.  I propose that we remove these structures and update the getter methods to query the sites in the tiles to get the methods (or remove them entirely if they are unused).

**Comment by DallonTG** [comment]
Addressed with PR #315.
