### ISSUE TITLE
Vivado Interface does not generate correct route string for long lines

### ISSUE THREAD

**Issue by mjc31511** [byuccl/RapidSmith2#272]
When trying to import a design generate using RapidSmith2 I noticed that nets with routes including long lines would not import. It looks like RapidSmith is using the correct wires, but it does not identify the correct node, or includes wires that are not nodes. Here is a summary of what I have found:
'LV_L9' - Wire not needed (its parent, which is already in the route string, is the node which connects to the sink)
'LV9' - Same as above
'LH6' - Same as above
'LH0' - Wrong node (this is a wire not the node that Vivado expects)
'LV_L0' - Same as 'LH0'

This was observed using Vivado 2016.4/2017.1 (I used both to see if it was a version issue).

**Comment by trharoldsen** [comment]
@mjc31511 Can you confirm that pr #294 fixes this issue so we can close this.

**Comment by nelsobe** [comment]
Was this fixed in #294?

**Comment by mjc31511** [comment]
I'm working on integrating and testing the changes of #294. It'll take about a week to test.

**Comment by mjc31511** [comment]
I have tested the changes of #294. It looks like the long line issues were resolved. However, there are now issues with atennas on some of the lines. I have talked to @DallonTG and he thinks he knows what the cause of this issue is.
