### ISSUE TITLE
getSubcells is not implemented

### ISSUE THREAD

**Issue by trharoldsen** [byuccl/RapidSmith2#88]
What support/requirements do we have for subcells?

**Comment by trharoldsen** [comment]
Thomas, can you comment on this.  I believe you handled all of the macro stuff and we can remove getsubcells method?

**Comment by ttown523** [comment]
This is now `getInternalCells`. The function can be removed.

**Comment by trharoldsen** [comment]
Can someone take 1 minute to remove the Cell:getSubcells method.
